---
- name: Configure Web Servers
  hosts: web_servers
  become: true
  vars:
    ansible_become_pass: "123456"

  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
