---
- name: Configure Web Servers
  hosts: web_servers
  become: true
  vars:
    ansible_become_pass: "123456"

  tasks:
    - name: Copy custom index.html file
      copy:
        src: index.html  # Assuming the index.html is in the current directory
        dest: /var/www/html/index.html  # Adjust the destination based on your Nginx configuration

    - name: Ensure Nginx is installed
      package:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
