---
- name: Send configuration commands to Telnet Servers
  hosts: telnet_servers
  gather_facts: no

  tasks:
    - name: Configure IOS device
      ansible.netcommon.telnet:
        user: root
        password: 123456
        login_prompt: 'Username: '
        prompts:
          - '[>#]'
        command:
          - terminal length 0
          - configure terminal
          - hostname ios01
      register: config_result

    - name: Print configuration result
      debug:
        var: config_result.stdout_lines

- name: Run show commands
  hosts: ios_devices  # Replace with your target hosts or group
  gather_facts: false  # Disable gathering facts for this example

  tasks:
    - name: Run show commands on IOS device
      ansible.netcommon.telnet:
        user: cisco
        password: cisco
        login_prompt: 'Username: '
        prompts:
          - '[>#]'
        command:
          - terminal length 0
          - show version
      register: show_result

    - name: Print show result
      debug:
        var: show_result.stdout_lines
