---
- name: Telnet Connection Playbook
  hosts: telnet_servers
  gather_facts: no  # Since Telnet doesn't require facts gathering
  connection: local  # Use a local connection

  tasks:
    - name: Install ansi2txt (aha)
      apt:
        name: aha
        state: present
      become: true

    - name: Telnet Connection
      shell:
        cmd: |
          { sleep 1; echo "root"; sleep 1; echo "123456"; sleep 1; echo "pwd"; sleep 1; echo "uptime"; sleep 1; } | telnet {{ inventory_hostname }} | aha --no-header > results/telnet_output_{{ inventory_hostname }}.txt
      register: telnet_result
      ignore_errors: true

